dist: xenial
language: python
python:
  - "3.7"
  - "3.7-dev"
install:
  - make dev
script:
  - python -m pip install -U pip setuptools wheel
  - pip install -U numpy scipy scikit-learn
  - make test
notifications:
  email:
    on_success: never
    on_failure: always
